name = "Crystal"
grammar = "crystal"
path_suffixes = ["cr"]
line_comments = ["# "]
language_servers = ["crystalline"]

[formatter]
external = { command = "crystal", arguments = ["tool", "format", "-"] }
